# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(battery vscode pip python git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

source ~/.config/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh

# antigen config
source $HOME/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

#antigen bundle marlonrichert/zsh-autocomplete

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle heroku
antigen bundle history
antigen bundle dirhistory
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply


alias vim='NVIM_APPNAME="kickstart-nvim" nvim'

# Get the hostname of the machine
HOSTNAME=$(hostname)

# Check if the hostname matches your work lapto"Uif [[ $HOSTNAME == "powerbook" ]]; then
if [[ $HOSTNAME == "Powerbook-Jolly" ]]; then
    alias mo="make onboard"
    alias soc="cd /home/jolly/Documents/SOC"
    alias gitdl="cd /home/jolly/Downloads/git"
    alias tfmdr="cd /home/jolly/Documents/Terraform/gcp-tf-service-mdr"
    alias rule_pr="gh pr create --fill --body-file .github/PULL_REQUEST_TEMPLATE/rule.md"
    alias tune_pr="gh pr create --fill --body-file .github/PULL_REQUEST_TEMPLATE/tune.md"
    alias dotedit="vim ~/Documents/Dot-Files"
    alias soc="cd ~/Documents/SOC"
    alias rules="cd ~/Documents/SOC/rules"
    alias pup="cd ~/Documents/SOC/pipeline-utils-package"
    alias aptupd="sudo apt-get update && sudo apt update"
    alias aptupg="sudo apt-get upgrade -y && sudo apt upgrasy -y"

    # Exports
    export PATH="/home/jolly/.local/bin:$PATH"
fi

# Check if the hostname matches your personal laptop
if [[ $HOSTNAME == "MacBook-Pro-van-Joris.local" ]]; then
    # Add aliases and configurations specific to your personal laptop here
    alias bu="brew update && brew upgrade"
    alias desosa="cd ~/Documents/1.\ Projects/MSC-CS/Courses/CS4505/desosa2024x"
    alias msc="cd ~/Documents/1.\ Projects/MSC-CS"
    alias dotedit="vim ~/Documents/Dev_env/Dot-Files"
    alias projects="cd ~/Documents/1.\ Projects/"
    alias resources="cd ~/Documents/3.\ Resources/"
    source ~/Documents/1.\ Projects/MSC-CS/Courses/CS4505/team-47/.env
fi

if [[ $HOSTNAME == "Joriss-Air" || $HOSTNAME == "Joriss-MacBook-Air.local" ]]; then
    if [[ -e "${HOME}/.1password/agent.sock" ]]; then
        export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
    fi
    alias bu="brew update && brew upgrade"
    alias mo='make onboard SSH_AUTH_SOCK="$(colima ssh printenv SSH_AUTH_SOCK)"'
    alias mdev='make dev SSH_AUTH_SOCK="$(colima ssh printenv SSH_AUTH_SOCK)"'
    alias madmin='make admin SSH_AUTH_SOCK="$(colima ssh printenv SSH_AUTH_SOCK)"'
    alias soc="cd ~/Documents/SOC"
    alias rule_pr="gh pr create --fill --body-file .github/PULL_REQUEST_TEMPLATE/rule.md"
    alias tune_pr="gh pr create --fill --body-file .github/PULL_REQUEST_TEMPLATE/tune.md"
    alias dotedit="vim ~/Documents/Dot-Files"
    alias soc="cd ~/Documents/SOC"
    alias rules="cd ~/Documents/SOC/rules"
    alias pup="cd ~/Documents/SOC/pipeline-utils-package"
    alias projects="cd ~/Documents/1.\ Projects/"
fi


export GPG_TTY=$(tty)

# Source fzf (requirement is that it is installed)
source <(fzf --zsh)
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source $HOME/.config/zsh/p10k.zsh

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

export ZSH_COLORIZE_TOOL=chroma

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
